import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LiffInitializer from "@/components/LiffInitializer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Check-jai App",
  description: "Generated by กลุ่มงานสุขภาพดิจิทัล สสจ.อุบล",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <main className="min-h-dvh w-full bg-white">
        {children}
        </main>
        <LiffInitializer />
      </body>
    </html>
  );
}
